# Generated by Django 5.0.1 on 2024-02-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='title',
            field=models.CharField(default='Untitled Itinerary', max_length=200),
        ),
    ]
