# Generated by Django 5.0.1 on 2024-02-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_alter_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='event_id',
        ),
    ]
